### ISSUE TITLE
Personnalize each cell

### ISSUE THREAD

**Issue by ben-j69** [roomorama/Caldroid#14]
I'm building a a calendar with 3 kinds of cell, normal cells, cells with price and cells with amount in percentage (see the picture).

I added an ArrayList of my cells, order by date in the Adapter. 

It's working fine for the selected month, but when i change the month the method getNewDatesGridAdapter is called and i can't figure how to use my array to build the display.

Do you think there is a better way to do this?
![device-2013-04-16-100637](https://f.cloud.github.com/assets/4158447/384924/9c59356a-a66c-11e2-9739-7de99761aba6.png)

**Comment by sonagara** [comment]
Hi @thomasdao Thank very much for your great work. I doing same like @sn4psh0t.

## Map<String, String> dates= (Map<String, String>) extraData.get("DATES");

--//same as your adapter

```
String currentDate = String.format("%02d", dateTime.getDay()) + "/" + dateTime.getMonth() + "/" + dateTime.getYear();
    if (dates.containsKey(currentDate)) {
        tv2.setText("hey");
        cellView.setBackgroundResource(com.caldroid.R.color.caldroid_sky_blue);
    } else {
        //tv2.setText("hi");
        //tv2.setBackgroundResource(...); // Your normal background
    }
    tv1.setText(" " + dateTime.getDay());
```

this work perfactly
this is screen shot 

![screenshot_20160714-181246](https://cloud.githubusercontent.com/assets/6158809/16839850/f29c2170-49ee-11e6-9b25-d7ca794e9140.png)

but when I change month than I get like this.

![screenshot_20160714-181645](https://cloud.githubusercontent.com/assets/6158809/16839896/359b9bd6-49ef-11e6-8463-a025cc7796d3.png)

![screenshot_20160714-181754](https://cloud.githubusercontent.com/assets/6158809/16839907/4fed3cce-49ef-11e6-8ec8-245735a6ede7.png)

every next 4 month I get text "hey".
I dont know where is it come. 
Please Help

Thank you

**Comment by LinhNHDev** [comment]
> Hi @thomasdao Thank very much for your great work. I doing same like @sn4psh0t.
> 
> ## Map<String, String> dates= (Map<String, String>) extraData.get("DATES");
> --//same as your adapter
> 
> ```
> String currentDate = String.format("%02d", dateTime.getDay()) + "/" + dateTime.getMonth() + "/" + dateTime.getYear();
>     if (dates.containsKey(currentDate)) {
>         tv2.setText("hey");
>         cellView.setBackgroundResource(com.caldroid.R.color.caldroid_sky_blue);
>     } else {
>         //tv2.setText("hi");
>         //tv2.setBackgroundResource(...); // Your normal background
>     }
>     tv1.setText(" " + dateTime.getDay());
> ```
> 
> this work perfactly
> this is screen shot
> 
> ![screenshot_20160714-181246](https://cloud.githubusercontent.com/assets/6158809/16839850/f29c2170-49ee-11e6-9b25-d7ca794e9140.png)
> 
> but when I change month than I get like this.
> 
> ![screenshot_20160714-181645](https://cloud.githubusercontent.com/assets/6158809/16839896/359b9bd6-49ef-11e6-8463-a025cc7796d3.png)
> 
> ![screenshot_20160714-181754](https://cloud.githubusercontent.com/assets/6158809/16839907/4fed3cce-49ef-11e6-8ec8-245735a6ede7.png)
> 
> every next 4 month I get text "hey".
> I dont know where is it come.
> Please Help
> 
> Thank you

you should set tv2.setText("") before you get ExtraData & set tv2.setText(your_data);
