### ISSUE TITLE
NoClassDefFoundError: com.caldroid.R$layout

### ISSUE THREAD

**Issue by yacklebeam** [roomorama/Caldroid#16]
I'm attempting to use the Caldroid library, and have added all the source files to my current project.  However, upon deployment, I receive a fatal error every time I try to show a calendar (using the CaldroidFragment).

The error is java.lang.NoClassDefFoundError: com.caldroid.R$layout
 at com.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:683).

Does anyone know of a possible fix?  I can provide any other info if needed.

Thanks.

**Comment by androleaven** [comment]
Hey,Hello sir..Sir Same problem persist with android studio 1.0.2..I added caldroid.jar as an library module in my application.Is it ok?
