### ISSUE TITLE
How to adjust height depending on available space?

### ISSUE THREAD

**Issue by TomislavHorvat** [roomorama/Caldroid#160]
I am having problems with displaying CaldroidFragment when I need it to fit in a FrameLayout that is half a screen heigh. This FrameLayout does not use fixed values, rather it uses weight. 

In the Frame Layout I inflate a layout xml file containing a LinearLayout with wrap_content for width and height, and everything loads fine, the date GridView though goes out of bounds and is scrollable. I have tried to implement my own xml for cell layout and that works fine too, but then I have space beneath the date GridView.

As soon as I change the height parametar of the Linearlayout in which the CaldroidFragment is put to fill_parent, the month display is shown the weekdays are shown but the date GridView is not. I would like some tips or instructions on how to modify CaldroidFragment behavior so that the date GridView always fits the space available

**Comment by zyavrik** [comment]
@TomislavHorvat How did you get InfiniteViewpager's height in the custom grid adapter?

**Comment by zyavrik** [comment]
Answer to my own question: parent.getHeight()
