### ISSUE TITLE
change color of cell border

### ISSUE THREAD

**Issue by shalinipk** [roomorama/Caldroid#166]
Is it possible to change the cell border color ?

Here is what's happening:

If user clicks on a cell, I set the back ground color of the cell to something else - say blue.
If user clicks on current date, the cell background color changes to blue.

So far so good.

However, when user clicks on another cell, the border color (default red) of current date is not restored.

Btw, thanks a lot for the amazing calendar interface.

**Comment by webaport** [comment]
Answer <a href="https://github.com/roomorama/Caldroid/issues/188">here</a>

In your project:

1) Create your_custom_grid_fragment.xml in layout folder

```
<?xml version="1.0" encoding="utf-8"?>
<GridView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/calendar_gridview"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:gravity="center_horizontal"
    android:numColumns="7"
    android:padding="1dp"
    android:stretchMode="columnWidth"
    android:horizontalSpacing="1dp"
    android:verticalSpacing="1dp"
    style="?styleCaldroidGridView"
    android:background="@android:color/transparent"/>
```

Set android:background = transparent in my case (or change padding and other if need)

2) Create CustomGridFragment.java
```java
public class CustomGridFragment extends CaldroidFragment {
    @Override
    protected int getGridViewRes() {
        return R.layout.your_custom_grid_fragment;
    }
}
```

3) Change initialization string from
```caldroidFragment = new CaldroidFragment();```
to
```caldroidFragment = new CustomGridFragment();```
