### ISSUE TITLE
Problem when using Theme.NoTitleBar

### ISSUE THREAD

**Issue by SkeeterWang** [roomorama/Caldroid#190]
When using Theme.NoTitleBar,
there are two background colors show as state_pressed.

Even if I set MinDate and MaxDate, 
It seems that the invalid dates are clickable 'cause of the pressed background show anyway.

Is it possible to solve this problem?

Thanks for the useful library anyway.

**Comment by LOG-TAG** [comment]
@SkeeterWang have tried this https://github.com/roomorama/Caldroid/issues/266#issuecomment-106163901 use theme like this!! works fine for me!!

**Comment by thomasdao** [comment]
This issue is now fixed with latest version 2.2.0
