### ISSUE TITLE
Event on day from database

### ISSUE THREAD

**Issue by raghunandankavi2010** [roomorama/Caldroid#191]
```
      final CaldroidListener listener = new CaldroidListener() {

        @Override
        public void onSelectDate(Date date, View view) {
        }

        @Override
        public void onChangeMonth(int month, int year) {

            String text = "month: " + month + " year: " + year;
            String monthS = String.valueOf(month);
            String yearS = String.valueOf(year);

            String[] args = { monthS , yearS }; 
            c= CaldroidSampleActivity.this.getContentResolver().query(CalendarProvider.CONTENT_URI,
                    new String[] {CalendarProvider.ID,CalendarProvider.EVENT,
                    CalendarProvider.DESCRIPTION,CalendarProvider.LOCATION,
                    CalendarProvider.YEAR,CalendarProvider.MONTH,CalendarProvider.DAY,
                    CalendarProvider.HOURS,CalendarProvider.MINUTES},"month=? and year=?",args, null);
            new GetEvents().execute();

        }

        @Override
        public void onLongClickDate(Date date, View view) {
        }

        @Override
        public void onCaldroidViewCreated() {
            if (caldroidFragment.getLeftArrowButton() != null) {

            }
        }

    };
```

In AsyncTask i fetch the events from ContentProvider based on month and the year.

```
   private class GetEvents extends AsyncTask<Void,Void,ArrayList<Event>>{

    @Override
    protected ArrayList<Event> doInBackground(Void... params) {
        events.clear();



        if( c.moveToFirst()){
            do{
                Event event = new Event();

                        event.setEVENT(c.getString(c.getColumnIndex(CalendarProvider.EVENT)));
                        event.setLOCATION(c.getString(c.getColumnIndex(CalendarProvider.LOCATION)));
                        event.setDESCRIPTION(c.getString(c.getColumnIndex(CalendarProvider.DESCRIPTION)));  
                        event.setYEAR(c.getString(c.getColumnIndex(CalendarProvider.YEAR)));

                        event.setMONTH(c.getString(c.getColumnIndex(CalendarProvider.MONTH)));
                        event.setDAY(c.getString(c.getColumnIndex(CalendarProvider.DAY)));
                        event.setHOURS(c.getString(c.getColumnIndex(CalendarProvider.HOURS)));
                        event.setMINUTES(c.getString(c.getColumnIndex(CalendarProvider.MINUTES)));
                        events.add(event);
                    }while(c.moveToNext()); 
                    c.close();
        }



        return events;
    }
    @Override
    protected void onPostExecute(ArrayList<Event> result){


        for(int i=0;i<result.size();i++)
        {

        int day = Integer.parseInt(result.get(i).getDAY());  //25
        int month = Integer.parseInt(result.get(i).getMONTH()); //12
        int year = Integer.parseInt(result.get(i).getYEAR()); // 1988

        Calendar c = Calendar.getInstance();
        c.set(year, month-1, day, 0, 0);  
        Date greenDate = c.getTime();
        ;

        if (caldroidFragment != null) {

            caldroidFragment.setBackgroundResourceForDate(R.color.blue,greenDate);

        }
        }

    }
}
```

The problem

After fetching the events form database i set the color to the date. 

Example : On Jan 1 2015 i have a event. So i change the color of the date. But this change is visible once i move to Feb and come back to Jan.  I am looking at the source and trying to figure out the issue.

This issue is not seen if i fetch events from database all at a time which is time consuming. So i would prefer fetching events based on month and year.

**Comment by jithea23** [comment]
hi there, i copied your codes but unfortunately i encounter many errors, like the variable 'events' and Event event = new Event(); it says its not in public and cannot be accessed from outside package, help me please..

**Comment by raghunandankavi2010** [comment]
where did you have that. Event is a model class. It has getter and setters

**Comment by jithea23** [comment]
aw that's why I'm having those errors.. I thought it was from CalendarContract.Event?, what your codes  in your Event model class? can we have a little conversation in skype please? I really need to finish my thesis this month :(

**Comment by jithea23** [comment]
can I have your codes in your Event model class please?, I'm using your codes above in getting events in database, I really having a hard time coding.

**Comment by raghunandankavi2010** [comment]
public class Event {

	private String EVENT;
	private String LOCATION;
	private String DESCRIPTION;// cal.set(2015,12, 22, 6, 5);
	private Long startDate;
	private Long endDate;
	
//	private String YEAR;
//	private String MONTH;
//	private String DAY;
//	private String HOURS;
//	private String MINUTES;
	private String ID;

	public String getEVENT() {
		return EVENT;
	}

	public void setEVENT(String eVENT) {
		EVENT = eVENT;
	}

	public String getLOCATION() {
		return LOCATION;
	}

	public Long getStartDate() {
		return startDate;
	}

	public void setStartDate(Long startDate) {
		this.startDate = startDate;
	}

	public Long getEndDate() {
		return endDate;
	}

	public void setEndDate(Long endDate) {
		this.endDate = endDate;
	}

	public void setLOCATION(String lOCATION) {
		LOCATION = lOCATION;
	}

	public String getDESCRIPTION() {
		return DESCRIPTION;
	}

	public void setDESCRIPTION(String dESCRIPTION) {
		DESCRIPTION = dESCRIPTION;
	}

//	public String getYEAR() {
//		return YEAR;
//	}
//
//	public void setYEAR(String yEAR) {
//		YEAR = yEAR;
//	}
//
//	public String getMONTH() {
//		return MONTH;
//	}
//
//	public void setMONTH(String mONTH) {
//		MONTH = mONTH;
//	}
//
//	public String getDAY() {
//		return DAY;
//	}
//
//	public void setDAY(String dAY) {
//		DAY = dAY;
//	}
//
//	public String getHOURS() {
//		return HOURS;
//	}
//
//	public void setHOURS(String hOURS) {
//		HOURS = hOURS;
public class Event {

	private String EVENT;
	private String LOCATION;
	private String DESCRIPTION;// cal.set(2015,12, 22, 6, 5);
	private Long startDate;
	private Long endDate;
	
	private String ID;

	public String getEVENT() {
		return EVENT;
	}

	public void setEVENT(String eVENT) {
		EVENT = eVENT;
	}

	public String getLOCATION() {
		return LOCATION;
	}

	public Long getStartDate() {
		return startDate;
	}

	public void setStartDate(Long startDate) {
		this.startDate = startDate;
	}

	public Long getEndDate() {
		return endDate;
	}

	public void setEndDate(Long endDate) {
		this.endDate = endDate;
	}

	public void setLOCATION(String lOCATION) {
		LOCATION = lOCATION;
	}

	public String getDESCRIPTION() {
		return DESCRIPTION;
	}

	public void setDESCRIPTION(String dESCRIPTION) {
		DESCRIPTION = dESCRIPTION;
	}



	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}
}

**Comment by jithea23** [comment]
Great! thank you so much! and your 'result' model class too have also getter?

**Comment by jithea23** [comment]
i have a problem here:

 c= CalendarActivity.this.getContentResolver().query(CalendarContract.Events.CONTENT_URI,
                        new String[] {CalendarContract.Events._ID,CalendarContract.Events.TITLE,
                                CalendarContract.Events.DESCRIPTION,CalendarContract.Events.EVENT_LOCATION,
                                CalendarContract.Events.DTSTART, CalendarContract.Events.DTEND},"month=? and year=?",args, null);
                new GetEvents().execute();

it says : 
 Caused by: android.database.sqlite.SQLiteException: no such column: month (code 1): , while compiling: SELECT _id, title, description, eventLocation, dtstart, dtend FROM view_events WHERE (lastSynced = 0 AND (month=? and year=?))

**Comment by jithea23** [comment]
and Asynctask runtimeException: An error occured while exeucuting doinBackgroud and giving NullPointerException at this codes:

 private class GetEvents extends AsyncTask<Void,Void,ArrayList<Event>>{
        ArrayList<Event> events;
        @Override
        protected ArrayList<Event> doInBackground(Void... params) {
            events.clear();

            if( c.moveToFirst()){
                do{
                    Event event = new Event();

                    event.setEVENT(c.getString(c.getColumnIndex(CalendarContract.Events.TITLE)));
                    event.setLOCATION(c.getString(c.getColumnIndex(CalendarContract.Events.EVENT_LOCATION)));
                    event.setDESCRIPTION(c.getString(c.getColumnIndex(CalendarContract.Events.DESCRIPTION)));
                    event.setStartDate(c.getLong(c.getColumnIndex(CalendarContract.Events.DTSTART)));
                    event.setEndDate(c.getLong(c.getColumnIndex(CalendarContract.Events.DTEND)));

                    events.add(event);
                }while(c.moveToNext());
                c.close();
            }

            return events;
        }
        @Override
        protected void onPostExecute(ArrayList<Event> result){


            for(int i=0;i<result.size();i++)
            {

                int day = Integer.parseInt(result.get(i).getDay());  //25
                int month = Integer.parseInt(result.get(i).getMonth()); //12
                int year = Integer.parseInt(result.get(i).getYear()); // 1988

                Calendar c = Calendar.getInstance();
                c.set(year, month-1, day, 0, 0);
                Date greenDate = c.getTime();
                ;

                if (caldroidFragment != null) {

                    caldroidFragment.setBackgroundResourceForDate(R.color.BlueViolet,greenDate);

                }
            }

        }
    }
}

**Comment by jithea23** [comment]
hey Sir! Why is it I am getting a result of 0? I put a toast inside the onPostExecute and I found out that it gives a result of 0, help sir..

@Override
        protected void onPostExecute(ArrayList<Event> result) {

            Toast.makeText(getApplicationContext(),
                    "result " + (result.size()),
                    Toast.LENGTH_SHORT).show();
            for (int i = 0; i < result.size(); i++) {
                int day = Integer.parseInt(result.get(i).getDay());  //25
                int month = Integer.parseInt(result.get(i).getMonth()); //12
                int year = Integer.parseInt(result.get(i).getYear()); // 1988

                Calendar c = Calendar.getInstance();
                c.set(year, month-1, day, 0, 0);
                Date greenDate = c.getTime();


                if (caldroidFragment != null) {

                    caldroidFragment.setBackgroundResourceForDate(R.color.BlueViolet, greenDate);

                }

            }

        }
