### ISSUE TITLE
Change date programaticaly

### ISSUE THREAD

**Issue by rincyrose** [roomorama/Caldroid#193]
I want to change the year month and date programmatically. I have selecting a date from datepicker and setting the caldroid date by 
caldroidFragment.setCalendarDate(selectedDate);
But it is changing only the calendar heading not the actual month view.
Currently i have month view with date 27/11/2014.
I tried to change to 25/02/2016.The heading will become February 2016.But month view will be same as before(November 2014) and when i click next arrow in header its going to December 2014 instead of  march 2016.

**Comment by antimoz89** [comment]
You have to use `moveToDate(selectedDate)` to update both the heading and the month view.

**Comment by thomasdao** [comment]
@antimoz89 thanks for helping out :+1:
