### ISSUE TITLE
Hide the month title text view

### ISSUE THREAD

**Issue by wuzesheng** [roomorama/Caldroid#195]
Hi,
  In my project, I want to hide the month title text view, I read through the whole document and found nothing can help. Does there anybody know how to hide the month title text view?

**Comment by MathieuHillion** [comment]
Hi wuzesheng, 
I'm trying to use your code. I add it inside the Caldroid fragment code from the Calroid project, but it does not seem to take it into account. How can I use your code, in order to remove the title from the caldroidFragement. 

Thanks a lot.
