### ISSUE TITLE
Show extra data in calender cells

### ISSUE THREAD

**Issue by Ravikiran357** [roomorama/Caldroid#206]
Hi,
I would like to know if there is an API to add extra information like a number to fit in the date cell in the calender view. For example:
<pre>Sun   Mon   Tue
3      4      5 ....
(3)   (2)    (6)       ------- Extra data 
---------------------
10    11     12 ....
(3)   (7)    (4)       ------- Extra data 
</pre>
and so on, if there isn't any API can you suggest how I might be able to achieve this with the Caldroid library.

Thanks.

**Comment by antimoz89** [comment]
You must provide a custom layout and adapter as referred on [Allow customized cell for the dates gridView](https://github.com/roomorama/Caldroid#allow-customized-cell-for-the-dates-gridview).

Take a look at `CaldroidSampleActivity` to understand how custom adapter works.

As a hint, you must create a new layout with 2 `TextView`s, one for date and one for extra data. Then for extra data, you could use `HashMap<Date, Integer>` to map between the date and number. Then on the custom adapter, get the extra data, then process the data from the `HashMap`.
