### ISSUE TITLE
Border around day is invisible on dates with background

### ISSUE THREAD

**Issue by MonkeySon** [roomorama/Caldroid#207]
Hello,

I got the issue that if the current date has a custom background, the border around the day in the calendar is not visible.

At first i forgot the refreshView() method, but it didn't change anything after i added it.

        caldroidCalendar = new CaldroidFragment();

        Bundle args = new Bundle();
        Calendar cal = Calendar.getInstance();
        args.putInt(CaldroidFragment.START_DAY_OF_WEEK, CaldroidFragment.MONDAY);
        args.putInt(CaldroidFragment.MONTH, cal.get(Calendar.MONTH) + 1);
        args.putInt(CaldroidFragment.YEAR, cal.get(Calendar.YEAR));
        args.putBoolean(CaldroidFragment.ENABLE_SWIPE, true);
        args.putBoolean(CaldroidFragment.SHOW_NAVIGATION_ARROWS, false);
        args.putBoolean(CaldroidFragment.SIX_WEEKS_IN_CALENDAR, true);

        caldroidCalendar.setArguments(args);

        if (caldroidCalendar != null && commissionList != null) {
            for (commission com : commissionList) {
                try {
                    if (com.isNightShift()) {
                        caldroidCalendar.setBackgroundResourceForDate(android.R.color.holo_blue_dark, formatter.parse(com.getDate()));
                    } else {
                        caldroidCalendar.setBackgroundResourceForDate(R.color.asb_work, formatter.parse(com.getDate()));
                    }
                    if (com.hasNote()) {
                        caldroidCalendar.setTextColorForDate(android.R.color.holo_red_dark, formatter.parse(com.getDate()));
                    }
                } catch (ParseException e) {

                }
            }
        }

        caldroidCalendar.refreshView();

        android.support.v4.app.FragmentTransaction t = getSupportFragmentManager().beginTransaction();
        t.replace(R.id.layout_calendar, caldroidCalendar);
        t.commit();

that's the code for adding caldroidCalendar.
Screenshots on request.

Thanks for helping,
MonkeySon

**Comment by thomasdao** [comment]
You should use a `<shape>` drawable to have both border and background color. You can see here for more detail http://developer.android.com/guide/topics/resources/drawable-resource.html
