### ISSUE TITLE
putting events in caldroid

### ISSUE THREAD

**Issue by jithea23** [roomorama/Caldroid#208]
hello sir good day!.. I am new in developing android apps, i try this caldroid and luckily I managed to run it successfully :) 
Is it possible to add events that will get from database?, because I am creating an app (for our thesis) that have School Calendar with Events, and whenever the user tap those dates that having an event, it'll pop up the description or put the description below will do.. I hope you get my concern sir.. God bless :)

**Comment by thomasdao** [comment]
You can read that in the documentation https://github.com/roomorama/Caldroid#display-user-events-on-caldroid
