### ISSUE TITLE
The name of the month doesn't appears in Android 4.1.2 Sony Xperia

### ISSUE THREAD

**Issue by cyrgui** [roomorama/Caldroid#210]
Congratulation for your great Calendar.
 
It work's very well on Android 4.4.2 but I've test it in my Sony Xperia 4.1.2 and in this device the month name doesn't appear as shown in the image.
![screenshot_2015-01-24-09-52-22](https://cloud.githubusercontent.com/assets/4137397/5886749/36638f3e-a3af-11e4-80c4-b4171b0e224a.png)

Please can you help me ?

**Comment by thomasdao** [comment]
@cyrgui does it happen on other phone as well or only Sony Xperia?

**Comment by cyrgui** [comment]
I only have a Sony XPERIA GOand a Samsung Galaxy (on the Galaxy it's Ok).
So I can't test it on other phone... May be it's due to the size of the
Xperia Screen ?

2015-01-28 2:32 GMT+01:00 Thomas Dao <notifications@github.com>:

**Comment by vamidi** [comment]
Hi there,

It is not only on your phone it happend to on my phone as well. On version 4.2.2 I still had the color of the month, but in version 5.0 I cant see it. I think it has to got to do with the appcompat theme because you can press on the month and then you see that it is just white.

**Comment by vamidi** [comment]
Ohw and btw I have a Galaxy note 3 so I dont think it is phone specific

**Comment by thomasdao** [comment]
I suspect this is because of Theme issue. I now set the title color to black explicitly, can you help to test if it works? You can use latest version 1.1.8 from Maven

**Comment by cyrgui** [comment]
Splendid ! Now it work's great on Sony Xperia. Thank's a lot, your calendar
is so nice !

2015-02-10 5:30 GMT+01:00 Thomas Dao <notifications@github.com>:

**Comment by vamidi** [comment]
Can you upload a piece of code of the theme that you have changed to make it work?

Thankyou in advance

**Comment by cyrgui** [comment]
I haven't change a piece of code :) I've only copy the calendar_view.xml
provided by Thomas and located at
https://github.com/roomorama/Caldroid/blob/master/caldroid/src/main/res/layout/calendar_view.xml

Then I've changed the old calendar_view.xml with the new one in the eclipse
library/res/layout

That's all !

2015-02-10 11:28 GMT+01:00 vamidi <notifications@github.com>:

**Comment by thomasdao** [comment]
@vamidi nothing special, I just set the color of textview to black https://github.com/roomorama/Caldroid/blob/master/caldroid/src/main/res/layout/calendar_view.xml#L30
