### ISSUE TITLE
Map events from Calendar Provider to dates

### ISSUE THREAD

**Issue by raghunandankavi2010** [roomorama/Caldroid#215]
I am trying to map events from calendar provider and color the dates based on events. I used asynctask to fetch events from calendar provider. Its very slow. I was thinking if its possible to have a better solution by using Loaders and CursorAdapter. However caldroid uses a BaseAdapter. Using asynctask works but its slow. The code i used is pretty simple. AsyncTask in onCreate of Activity. Once you fetch events from Calendar Provider set background to dates in onPostExecute. 

Note: The asynctask fetches all events at once. Its time consuming.

There must be a better way.

**Comment by raghunandankavi2010** [comment]
We can fetch events for fourth month just like dates. I haven't tested. But could that be a possible solution??

**Comment by raghunandankavi2010** [comment]
Well the suggestion seems to work. If the author can confirm this issue can be closed

**Comment by thomasdao** [comment]
Caldroid is just UI library, it does not connect to any Calendar Provider. After you fetch the events, make sure you set all the data (maxDate, minDate, disabledDates, etc) and only call `refreshViews()` at the end to update calendar appearance. 

If you don't want to fetch all events at once using AsyncTask, then just fetch event for one month. When user swipe to another month, you can listen to `CaldroidListener.onChangeMonth(int month, int year)` and load events for that month.
