### ISSUE TITLE
how set bitmap image

### ISSUE THREAD

**Issue by Eldqs** [roomorama/Caldroid#216]
I make thumbnail from dinamic video and I need to set Bitmap image in cell view of caldroid, but don't have a way how it do. Can you suggest a solution to this problem? Help me Please! Thank you before doing!

**Comment by thomasdao** [comment]
You can customize the cell as instruction here https://github.com/roomorama/Caldroid#allow-customized-cell-for-the-dates-gridview. 

Every caldroid fragment has a `HashMap`, retrieved by `caldroidFragment.getExtraData();`. You can put your thumbnail bitmap into this hash map, and access it in `getView` method of your custom adapter.

**Comment by Eldqs** [comment]
I am sorry, I just started doing the program for android, and don't understand how it may be it. please give me an example. Thank you

**Comment by Eldqs** [comment]
thank you, i maked it on samples
