### ISSUE TITLE
Every time required getview  everything is built with first

### ISSUE THREAD

**Issue by Eldqs** [roomorama/Caldroid#217]
I am  setting background everthing a cell and apply adapter, and where change  a month at in catlog seem repeat building for every day with first for five month, how can make that built only next month, because it is long.
sorry for my bad english.

**Comment by Eldqs** [comment]
when opening the progam getview invoked 150 times and change month getview invoked once again 150 times.

**Comment by Eldqs** [comment]
help me please, very long handled when scrolling, because it every time scrolling is make for 5  page, although already maked before scrolling

**Comment by thomasdao** [comment]
I don't really understand what's the issue here...
