### ISSUE TITLE
Fit Month View Only

### ISSUE THREAD

**Issue by AnkurJagani** [roomorama/Caldroid#218]
Hi..is it possible to create month view exactly like below. 

![screen568x568](https://cloud.githubusercontent.com/assets/7710697/6039055/e3c29184-ac88-11e4-960d-d43a382933e5.jpeg)

.........

Currently i am getting like below:

  
![device-2015-02-04-161549](https://cloud.githubusercontent.com/assets/7710697/6039074/0cf97cde-ac89-11e4-8753-d50699b43a1d.png)

Please give some brief and nice explanation.  Thank you in advance.

**Comment by AnkurJagani** [comment]
Month should display exact dates. should not display disabled dates of previous months. I hope you got my point. Please Note: I am not talking about selected dates.

**Comment by jithea23** [comment]
hi can you help me with those events?, how to show events at the bottom whenever the user select dates with events?

**Comment by AnkurJagani** [comment]
check my answer in your raised issue.

**Comment by thomasdao** [comment]
You can use below code, it will fit the month

`Bundle args = new Bundle();
args.putInt(CaldroidFragment. SIX_WEEKS_IN_CALENDAR, false);
caldroidFragment.setArguments(args);`
