### ISSUE TITLE
event show when user selects a date

### ISSUE THREAD

**Issue by jithea23** [roomorama/Caldroid#219]
![screenshot_2015-02-04-22-25-45](https://cloud.githubusercontent.com/assets/10572805/6042167/88a419dc-acbd-11e4-974f-f22b7130c620.png)

how to make this on onSelectDate method?, Those green marks are events from my database, What i want to do is if the user select those events, the corresponding event description will show below..

**Comment by AnkurJagani** [comment]
for that you need to inflate event decryption in list adapter. right now you might have Arraylist<String>. convert it to Arraylist<Object> and do accordingly.

**Comment by jithea23** [comment]
how to inflate event decryption?, sorry im new in developing android apps, can you provide me some code please?..

**Comment by thomasdao** [comment]
This issue is not Caldroid bug, you may find better help on StackOverflow
