### ISSUE TITLE
Update Gradle build tools

### ISSUE THREAD

**Issue by TheIronMarx** [roomorama/Caldroid#220]
com.android.tools.build:gradle:0.14.1 is dated. 1.0.1 should be used.

1.0.1 brought in some nice changes, but does require a tiny amount of tweaking elsewhere. Specifically, specifying applicationId in the defaultConfigs (in app-level build.gradle) is no longer allowed. 

This is a very small tweak, but ultimately worth it. For some users like myself who automate updating the build tools, working backwards is a pain. 

If need be, I can submit a pull request updating the build tools (along with a .gitignore tweak)

**Comment by thomasdao** [comment]
Thanks @TheIronMarx, I will update Maven soon
