### ISSUE TITLE
how can I get onSelectDate int position?

### ISSUE THREAD

**Issue by jithea23** [roomorama/Caldroid#222]
Whenever I add 'int position' it gives an error, is there any other way to get the selected date through position? Or any suggestions?

          @Override
            public void onSelectDate(Date date, View view) {

                final ListAdapter adapter = new SimpleAdapter(CalendarActivity.this, eventsList, R.layout.calendar_event_list, new String[]{TAG_PID,
                        TAG_EVENTTITLE,TAG_EVENTSTART,TAG_EVENTEND},
                        new int[]{R.id.pid, R.id.eventname, R.id.eventstart, R.id.eventend});
                ListView myList = (ListView) findViewById(android.R.id.list);
                myList.setAdapter(adapter);

                        HashMap<String, Object> obj = (HashMap<String, Object>) adapter.getItem(position);
                        String name = (String) obj.get("eventstart");
                        Log.d("Yourtag", name);

                caldroidFragment.setSelectedDates(date, date);

                caldroidFragment.refreshView();

            }

**Comment by thomasdao** [comment]
you can calculate the position from date in that month

**Comment by jithea23** [comment]
how can I calculate it? should I convert date to int?

**Comment by thomasdao** [comment]
For e.g: date 22 March should have position of 21 in the grid
