### ISSUE TITLE
Drawable issue on scrolling

### ISSUE THREAD

**Issue by edryer** [roomorama/Caldroid#223]
Setting a drawable on the current view using:

caldroidFragment.setBackgroundResourceForDate

and then swiping forward four months results in the drawable still being present (inifinity page issue?), removing this future (+4 months) drawable (via onMonthChange) results when swiping back to the drawable being removed from the original view...

Is there any simple way around this?

I guess I could use:

caldroidFragment.getBackgroundForDateTimeMap().clear();

and then setBackgroundResourceForDate again.... but this is not ideal for sure....

thanks!

**Comment by thomasdao** [comment]
If you want to clear the background for a certain date, you can try:

```java
DateTime dateTime = CalendarHelper.convertDateToDateTime(date);
caldroidFragment.getBackgroundForDateTimeMap().remove(dateTime);
caldroidFragment.refresh();

```

**Comment by edryer** [comment]
many thanks Thomas... this is ideal...
