### ISSUE TITLE
How replacing calendar1 works? 

### ISSUE THREAD

**Issue by geoemm** [roomorama/Caldroid#226]
I saw that on the layout there was a calendar1 linear layout but how is calendar1 populated? Since on the example code there is no "t.add(calendar1,caldroidfragment)" ?? 

Actually i searched the project and calendar1 isn't mentioned anywhere but on the layout.

I wanted to by pressing a button to show the calendar dialog and i used "t.attach" instead and it works.

**Comment by thomasdao** [comment]
You can checkout the sample activity https://github.com/roomorama/Caldroid/blob/master/caldroidSampleActivity/src/main/java/com/caldroidsample/CaldroidSampleActivity.java#L95
