### ISSUE TITLE
setBackgroundResource for range of dates

### ISSUE THREAD

**Issue by pcm992004** [roomorama/Caldroid#230]
Hi, I'm using Caldroid Library, it's great!!

I'm going to put events with a start date and a different end date, How can I put a background resource for all days in range?

Thanks..

**Comment by thomasdao** [comment]
You can set `CaldroidFragment.selectedBackgroundDrawable` to your own drawable, make sure you set it before you inflate Caldroid fragment. I will update documentation too.

**Comment by pcm992004** [comment]
I have an event with this values, name, start_date, end_date. I want to show all dates in range start_date-end_date ina a different color or with a custom drawable background.

I know to put background in only one date, but it's possible to put background in all dates in range at same time?

**Comment by thomasdao** [comment]
Yes you can, use something like:

```java
CaldroidFragment.selectedBackgroundDrawable = R.drawable.your_custom_selected_background;
```
