### ISSUE TITLE
refreshView doesn't work

### ISSUE THREAD

**Issue by Octavianus** [roomorama/Caldroid#232]
Hi, I'm using your lib and make a great calendar.

I already can change the background color and text statically,

But if I wanna change those things on the date I click on is not working.

final CaldroidListener listener = new CaldroidListener() {
			public void onSelectDate(Date date, View view) {
                                                caldroidFragment.setBackgroundResourceForDate(R.color.Blue,
		        			date);
		        			caldroidFragment.setTextColorForDate(R.color.White, date);
                                                caldroidFragment.refreshView();
			}
};

I already go through all the possible thread here but no one can solve this. For example:
https://github.com/roomorama/Caldroid/issues/117

What's the problem here?
Thanks!

**Comment by thomasdao** [comment]
did you set `caldroidFragment. setCaldroidListener(listener);`?
