### ISSUE TITLE
Shrink Caldroid using own layout not working. plz help

### ISSUE THREAD

**Issue by supsabhi** [roomorama/Caldroid#238]
HI,Thanks for great library,i want to adjust caldroid height without scroll,want to shrink the date cell.so instead of using sqaure textview i simply put the textview with width as wrap content and height as 30 dp but it is not working at all,changed many attributes but cell height is not getting manipulated,can you please help me ASAP.
Thanks and Regards,
Supriya

**Comment by thomasdao** [comment]
You can checkout the documentation:

```java
Bundle args = new Bundle();
args.putBoolean(CaldroidFragment.SQUARE_TEXT_VIEW_CELL, false);
caldroidFragment.setArguments(args);

```
