### ISSUE TITLE
Importing from google calendar

### ISSUE THREAD

**Issue by tavo92** [roomorama/Caldroid#245]
Hello, i am interesting in using Caldroid but i want to be able to import different google calendars (ie add the events to Caldroid generated calendar just by giving it the calendar id). As far as i see that is not possible, but it doesn't seem a hard feature to add. So... do you have support for this? If no... can i add it? :)

**Comment by thomasdao** [comment]
Caldroid is simply UI library, it won't have support for any special calendar. You are welcome to fork it to add your own features
