### ISSUE TITLE
Scroll after refresh

### ISSUE THREAD

**Issue by elena-kaiti** [roomorama/Caldroid#249]
Hello,
 I am using Caldroid but i have a problem. I hope you can help me. When i open a new activity and write something , when i return back the caldroid becomes scrollable.
Any idea how to solve this? Thanks a lot.!

![1](https://cloud.githubusercontent.com/assets/5496834/6925347/7896f58c-d7e7-11e4-9f01-d7be4193f6a3.jpg)
![2](https://cloud.githubusercontent.com/assets/5496834/6925349/789d7498-d7e7-11e4-99f4-e5793ffcc2d4.jpg)
![3](https://cloud.githubusercontent.com/assets/5496834/6925348/7897b2ec-d7e7-11e4-86a1-1ea0104b3814.jpg)

**Comment by thomasdao** [comment]
I don't think this's because of Caldroid. It's a fragment that resize according to the parent layout. Do you adjusting the parent layout when your activity returned?

**Comment by elena-kaiti** [comment]
Hey Thomas. Thanks for your help! The problem was keyboard in the new Activity.  Thats why Caldroid got scrolling!
