### ISSUE TITLE
Show week view(on scroll of events)

### ISSUE THREAD

**Issue by Prem19** [roomorama/Caldroid#251]
In month view, on selecting the date, am updating the list view on the same page(down) to show the relevant events.

But, I need to know on scrolling list view up how to show only Week(1 row)(which is selected) and scroll down display the month view again.

How to show week view on list scroll up and month view on scroll down. Any suggestions?

**Comment by thomasdao** [comment]
This is not Caldroid bug, you might have better answer asking on Stackoverflow
