### ISSUE TITLE
On rotation, the entire date grid gone missing.

### ISSUE THREAD

**Issue by neonwarge04** [roomorama/Caldroid#253]
I successfully built the application demo for Caldroid and it was great! But I created a sample activity of my own and when I rotate it the entire grid view gone missing. I rotate back again to see if it shows up again, but still its gone missing. This is not the case on the sample demo and I painstakingly follow what was on the short tutorial but nothing seem to work out for me.

At first I thought the problem is due to the CaldroidFragment being added into a viewpager but I went on creating a new entry-point stand alone activity and added fragment into that but the problem still persist.

**Comment by thomasdao** [comment]
You need to create a new CaldroidFragment instead of reusing the previous one, and restore states to this new CaldroidFragment

**Comment by neonwarge04** [comment]
Thanks thomas! That should do it.
