### ISSUE TITLE
Failed to resolve in grandle

### ISSUE THREAD

**Issue by jeanjn** [roomorama/Caldroid#256]
I'm try compile compile 'com.roomorama:caldroid:2.0' like maven and search inside android studio
and I try compile 'com.roomorama:caldroid:2.0.0'  too.

What's happends?

My dependencies :
dependencies {
    compile 'com.google.android.gms:play-services:6.5.87'
    compile files('libs/libGoogleAnalyticsServices.jar')
    compile files('libs/mail.jar')
    compile files('libs/activation.jar')
    compile files('libs/additional.jar')
    compile files('libs/gson-2.2.4.jar')
    compile 'com.roomorama:caldroid:2.0'
}

**Comment by thomasdao** [comment]
I tried `compile 'com.roomorama:caldroid:2.0.0'` and it works fine, not sure if this issue is because of Caldroid?

**Comment by jeanjn** [comment]
I'm sorry, I found a solution now, a needed put in grandle 
maven { url 'http://repo1.maven.org/maven2' }.
Now works fine.

Thanks and sorry.
