### ISSUE TITLE
Missing ability to make custom Caldroid fragment fill screen.

### ISSUE THREAD

**Issue by mobbren** [roomorama/Caldroid#258]
The primary layout file, `calendar_view.xml`, has its height set in XML: 

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
     android:layout_width="match_parent"
     android:layout_height="wrap_content"
     style="?styleCaldroidViewLayout"
     android:orientation="vertical" >`

This makes it impossible to make a Caldroid fragment take up an entire screen. There should be some functionality to make the component fit a given parent.

I've tried overriding the `onCreateView` method, and setting `LayoutParams` programmatically, each attempt to no avail.

**Comment by thomasdao** [comment]
feel free to fork it and customize the layout. PR is welcomed too
