### ISSUE TITLE
easiest way to set transparent background in Caldroid

### ISSUE THREAD

**Issue by tinoper** [roomorama/Caldroid#259]
What is the easiest way to setup transparent background using Caldroid .I already have an image as a app background.

Regards,

**Comment by thomasdao** [comment]
You may play with the custom theme, instead of using solid color, add some transparency to that color.

```xml
    <style name="CaldroidDefaultDarkGridView" parent="CaldroidDefaultGridView">
        <item name="android:background">@color/your_transparent_color</item>
    </style>
```
