### ISSUE TITLE
Hide cell border

### ISSUE THREAD

**Issue by raplider** [roomorama/Caldroid#261]
Hi/ how i can hide cell  border ? 
or set different color.  thanks

![photo_2015-04-29_13-37-35](https://cloud.githubusercontent.com/assets/4466505/7389274/0d0839f8-ee75-11e4-8ad2-98a78c850edc.jpg)

**Comment by langzi1206** [comment]
apologize for my English first

The borders aer not belong to calendar cells, it's the backgroud of the gridview which holds the calendar cells, and the backgroud of the layout which holds the gridview. So the tow related parts are bith in styles.xml: 
    <item name="styleCaldroidGridView">@style/CaldroidDefaultGridView</item>
and
    <item name="styleCaldroidViewLayout">@style/CaldroidDefaultCalendarViewLayout</item>

in "CaldroidDefaultGridView" style and "CaldroidDefaultCalendarViewLayout" style, set the "android:background" item with the same color of the backgourd color of calendar cell, then the borders should disappear.

ps:the background color of calendar cell is in /drawable/cell_bg.xml, or cell_bg_dark.xml for the dark theam

hope this would help

**Comment by MacNew** [comment]
<style name="CaldroidDefaultGridView">
        <item name="android:adjustViewBounds">true</item>
        <item name="android:horizontalSpacing">0dp</item>
        <item name="android:padding">0dp</item>
        <item name="android:verticalSpacing">0dp</item>
    </style>

**Comment by MacNew** [comment]
<style name="CaldroidDefaultGridView">
        <item name="android:adjustViewBounds">true</item>
        <item name="android:gravity">center_horizontal</item>
        <item name="android:listSelector">@null</item>
        <item name="android:background">@color/caldroid_white</item>
        <item name="android:horizontalSpacing">0dp</item>
        <item name="android:padding">0dp</item>
        <item name="android:verticalSpacing">0dp</item>
    </style>

**Comment by saiyeshwanth** [comment]
> apologize for my English first
> 
> The borders aer not belong to calendar cells, it's the backgroud of the gridview which holds the calendar cells, and the backgroud of the layout which holds the gridview. So the tow related parts are both in styles.xml:
> @style/CaldroidDefaultGridView
> and
> @style/CaldroidDefaultCalendarViewLayout
> 
> in "CaldroidDefaultGridView" style and "CaldroidDefaultCalendarViewLayout" style, set the "android:background" item with the same color of the backgourd color of calendar cell, then the borders should disappear.
> 
> ps:the background color of calendar cell is in /drawable/cell_bg.xml, or cell_bg_dark.xml for the dark theam
> 
> hope this would help

but how to add padding to cells
