### ISSUE TITLE
Setting background resource colour to particular dates changes if we swipe the months.

### ISSUE THREAD

**Issue by supsabhi** [roomorama/Caldroid#265]
Hi,
From JSON response,I am having list of weekends,list of disable dates,list of other holidays etc.What I am trying to do is,putting different colours to cell as per the code I receive.In AsyncTask I am parsing the response and on postexceute of it I am calling cadroidfragments setCustomResourceForDates() method.where on, oncreateview of fragment I am initializing the caldroid,and setting up listner for it also.and on caldroid's onChangeMonth , I am calling my AsyncTask.execute method as for each month data is different.What problem here coming is ,on first land all works good but as soon as I swipe pages and come back and forth then disable dates and weekend dates colours are getting overlapped.Plz Help me.
I ensured that data which is coming and which I am parsing is correct.
In attached screen shot,Gray
![1st_time_may_month_correct_display](https://cloud.githubusercontent.com/assets/5425322/7492212/8ebce588-f402-11e4-9f98-e2c0b6463589.png)
![2nd_time_may_omnth_wrong_display](https://cloud.githubusercontent.com/assets/5425322/7492222/9809f8d8-f402-11e4-9a42-3cbce9a49f66.png)

 colour displays weekend and brown colour is for not in month(disabled dates) if you see,in wrong image,weekend colour is getting overlapped on not in month colour.
Thanks in advance

**Comment by thomasdao** [comment]
Sorry please try to track down which issue belong specific to Caldroid so it's easier to fix
