### ISSUE TITLE
Month title missing

### ISSUE THREAD

**Issue by DavidH46** [roomorama/Caldroid#266]
![default](https://cloud.githubusercontent.com/assets/9254883/7555438/14df8980-f77e-11e4-8e7a-c97bc1b62932.PNG)
Thanks for sharing this wonderful work.
I'm just starting to use caldroid and my month title is missing.
I can't figure out why.
The grey rectangle in the upper-left hand corner seems to be "next month" arrow because it change to next month when I click it.
Any idea on how this is happening?

**Comment by thomasdao** [comment]
I never seen this issue before. Can you try Caldroid Sample on your phone? If the sample works, probably it's your code issue

**Comment by gwangyi** [comment]
I have same problem too. I had tried on Galaxy S3 with API level 19. It also has gone away in emulator, too.
In API level 22 and 10 w/ emulator, month title is shown well.

**Comment by DavidH46** [comment]
@thomasdao I believe it's because I use ActionBarActivity instead of FragmentActivity. But my actionbar needs to extends from actionbaractivity. Is there any way that I can get the best of both worlds? Thank you

**Comment by DavidBreskvar** [comment]
I have the same problem. I was changing the style of calendar and all of the sudden no more month title and the arrows were gone. I did a revert but that did not solve the problem.

**Comment by gwangyi** [comment]
I solved the problem: I copied style from CaldroidDefault to AppTheme and change parent to Base.Theme.AppCompat.Light.DarkActionBar. It seems that AppCompatActivity can't handle accurately when inner view or fragment has different theme from owner activity. I don't know why :(

**Comment by DavidBreskvar** [comment]
Could you give me an example? My AppTheme parent is currently Theme.AppCompat.NoActionBar.
Is there a chance to preserve that? I tried changing the theme in CaldroidDefault to AppTheme but no success.

**Comment by DavidBreskvar** [comment]
Ok, the problem actually is the new version of app compat library, which was upgraded from 22.0.0 to 22.1.1.
I reverted to last appcompat and the month title is again showing, but that should be somehow upgraded, to use the latest libraries available.

**Comment by gwangyi** [comment]
I have added some items to AppTheme style to make similar to CaldroidDefault in caldroid project.

<style name="AppTheme" parent="Base.Theme.AppCompat.Light.DarkActionBar">
        <item name="styleCaldroidViewLayout">@style/CaldroidDefaultCalendarViewLayout</item>
        <item name="styleCaldroidLeftArrow">@style/CaldroidDefaultLeftButton</item>
        <item name="styleCaldroidRightArrow">@style/CaldroidDefaultRightButton</item>
        <item name="styleCaldroidMonthName">@style/CaldroidDefaultMonthName</item>
        <item name="styleCaldroidGridView">@style/CaldroidDefaultGridView</item>
        <item name="styleCaldroidNormalCell">@style/CaldroidDefaultNormalCell</item>
        <item name="styleCaldroidSquareCell">@style/CaldroidDefaultSquareCell</item>
        <item name="styleCaldroidWeekdayView">@style/CaldroidDefaultWeekday</item>
    </style>

**Comment by LOG-TAG** [comment]
@gwangyi  saved my day !! :+1: now works fine !!!

**Comment by NitramTasu** [comment]
I had the same problem!!! thanks @gwangyi !!!

**Comment by acedward** [comment]
Same issue here. 
@DavidH46 solution worked for me. Thanks!

**Comment by azizimusa** [comment]
the solution provided by @gwangyi is working ! thank you very much.

**Comment by thomasdao** [comment]
Please use latest version `compile 'com.roomorama:caldroid:2.1.0'`, it should fix this issue

**Comment by matteolel** [comment]
Same problem with v2.1.0.
BTW the solution provided by @gwangyi is still working!

**Comment by fpr0001** [comment]
@gwangyi i love you
