### ISSUE TITLE
caldroid appcompat incompatibility

### ISSUE THREAD

**Issue by AntonioDascanio** [roomorama/Caldroid#269]
Hello,
I'm doing an application with navigation drawer, I have to use appcompatv7 so when i import caldroid library nothing works, but if I import only caldroid library all the code taken from the CaldroidSampleActivity is recognized but obviously the rest of the code give me problem.
Please can you help me in some way?
thank you!

**Comment by thomasdao** [comment]
I've never use Caldroid in nav drawer before, if anyone can make it work feel free to comment
