### ISSUE TITLE
Wrap Content not properly setting the height for the calendar

### ISSUE THREAD

**Issue by mielet** [roomorama/Caldroid#273]
For some reason in the XML when I set the height using wrap_content only the month row, and days of the week row are display and the rest is truncated. If I were to set a dp value for the height then that amount is properly displayed. Has anyone else encountered this or have any idea how to fix it? 

EDIT: I was wrong, it does not appear to be truncating the dates but rather collapsing the grid

**Comment by mielet** [comment]
Upon further research I see that this is having to do with the calendar being in a scrollView (issue #53) 

I believe I may have found a better solution to the vertical sizing on a scrollView, I believe by programatically changing the calendar's height by having it scaled to the current device's height there wouldn't be a need for multiple layouts. Something like this has given me luck.

LinearLayout linearCalendar = (LinearLayout)findViewById(R.id.calendarView);

    Display display = getWindowManager().getDefaultDisplay();
    Point size = new Point();
    display.getSize(size);

    // Storing the screen height into an int variable
    int height = size.y;
    int width = size.x;

    // Retrieves the current parameters of the layout and storing them in variable params

    ViewGroup.LayoutParams params = linearCalendar.getLayoutParams();

    // Re-setting the height parameter to .51 the max screen height

    params.height =  (int)Math.round(height*.51);
    params.width = (int)Math.round(width*.80);
Note that these are the scalings for my calendar only taking up 80% of my screen width, I believe that if you have the calendar's width as "match_parent" you need to use ~62% for the screen height.

**Comment by grennis** [comment]
Something still isnt right, why cant we wrap_content over the height of the calendar? Doing math to guesstimate the height seems like a very error-prone solution to me.

**Comment by thomasdao** [comment]
Hi all, finally I have fixed this issue in latest Caldroid 2.3.0, let me know if it works, thanks

**Comment by grennis** [comment]
Yes, it works. thanks
