### ISSUE TITLE
Landscape mode problem

### ISSUE THREAD

**Issue by RudraNirvan** [roomorama/Caldroid#28]
In CaldroidSample, on changing to landscape mode, the "Customize" and "Show Dialog" button disappear. So I added a scroll view to the whole layout. But after doing so, the calendar grid is no longer visible. Although the calendar arrow and date can be seen, the date grid is vanished. (the buttons are visible). So how to handle the grid when mode is changed to landscape?

**Comment by thomasdao** [comment]
I have fixed this issue in latest Caldroid 2.3.0, let me know if it works, thanks
