### ISSUE TITLE
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by anirbansAndroidDev** [roomorama/Caldroid#280]
Getting an error - 

Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

might be in this line - https://raw.githubusercontent.com/shamanland/gradle-mvn-push/cc18d56549cdea03f744b6fff27911569394073e/gradle-mvn-push.gradle

**Comment by abdallahalaraby** [comment]
In the library's build.gradle, remove this line
`apply from: 'https://raw.githubusercontent.com/shamanland/gradle-mvn-push/cc18d56549cdea03f744b6fff27911569394073e/gradle-mvn-push.gradle'`

this is used to upload to maven repository, which is not needed if you're not contributing to the project

**Comment by anirbansAndroidDev** [comment]
Yes I just deleted that line now it's working. thanks

**Comment by Dev-Jabin** [comment]
Thank you!

**Comment by mahendramahi** [comment]
check library and project build.gradle and comment this line if you found

apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'
