### ISSUE TITLE
Please add option to only view SHOW_NAVIGATION_ARROWS. 

### ISSUE THREAD

**Issue by azizimusa** [roomorama/Caldroid#283]
I don't know if this are already implemented. But I couldn't find it. It would be great if this plugin allow to only display navigation arrow and remove the calendar grid from display. But then, clicking on the date on the centre of navigation arrow would re-display the calendar grid.

**Comment by thomasdao** [comment]
You can subclass `CaldroidFragment` and add this feature yourself
