### ISSUE TITLE
Cannot selecting date on click in Custom cell

### ISSUE THREAD

**Issue by Ishaq01** [roomorama/Caldroid#284]
Hi..
I'm using caldroid with custom cell and make like this
![m](https://cloud.githubusercontent.com/assets/11646191/8372054/9719b3c6-1c09-11e5-9aaa-06b8a7fd1295.png)
I have a problem when I click the date with description, "onSelectDate" method not running
this different if i click the date without description, "onSelectDate" method running well

Please Help me.

**Comment by thomasdao** [comment]
This is because the view on your custom cell has consumed the touch and did not pass it to the gridview. You can find more info on StackOverflow

**Comment by Ishaq01** [comment]
Ok.
Thank thomas.

**Comment by hobbityoni** [comment]
Did you find a solution Ishaq01? I'm having the same problem.

Granted I'm new to Android and Caldroid and even Java, but I followed the CustomCell sample to the letter. And I can't get the onSelectDate triggered. By now I've tried the following:

1. Remove the background from my custom_cell layout. The result is that I do see an orange highlight animation when I click the cell but no highlighting after occurs and onSelectDate is not being called.
2. Set all view elements in custom_cell layout to clickable="false". The result is nothing happens, no onSelectDate is being triggered and no highlighting occurs.
3. Hooked the onTouch event and returned false for the cellView in the getview of the CaldroidGridAdapter. The result is the same as number 2.

I very much like to know how I can make the onSelectDate work again and also how to get the fancy highlighting that occurs on the click and long click of the cell.

If I need to provide you with some code, I will, just tell me what you need.

Thanks,

Yoni

**Comment by Ishaq01** [comment]
thanks yoni for your response.

No, I didn't find a solution. but I skip this problem until I getting
wonders in my mind.  😁

Nice to meet you Yoni.

**Comment by hobbityoni** [comment]
A few weeks ago I was a complete n00b to Android, but now I'm considering modifying the source myself. Caldroid is one of the few good customizable android calendar widgets out there. I really need this to work my way. Because I also don't like the fact that the grid is not stretching to match its parent. Once I get around to it I will post my code here somewhere. I know I should probably fork it here, but I'm also new to GitHub and still have no idea how this all works. :P
