### ISSUE TITLE
Month and Year hide

### ISSUE THREAD

**Issue by rrj12** [roomorama/Caldroid#286]
Hi, I am facing an issue. When i add "com.android.support:design:22.2.0" to the dependencies the Month and year are not getting displayed. Kindly look into the issue and reply.
on removing the dependency :
![screenshot_2015-07-01-00-36-11 1](https://cloud.githubusercontent.com/assets/6198642/8439553/7bd32a8c-1f8a-11e5-832c-676b8bd8663d.png)

on adding the dependecy :
![screenshot_2015-07-01-00-41-08 1](https://cloud.githubusercontent.com/assets/6198642/8439650/05869da4-1f8b-11e5-9ff4-440f5acc927d.png)

**Comment by azizimusa** [comment]
follow this :

https://github.com/roomorama/Caldroid/issues/266

**Comment by thomasdao** [comment]
Please use latest version compile 'com.roomorama:caldroid:2.1.0', it should fix this issue

**Comment by niranjan94** [comment]
+1
