### ISSUE TITLE
Navigation arrows style on Android prior to 5

### ISSUE THREAD

**Issue by Joqus** [roomorama/Caldroid#287]
I am facing a strange behaviour with the navigation arrows on Android version prior to 5. The are all grouped in the right. See the attached screen shot under the "Caldroid Sample". The arrows do now show properly. 

![caldroid_arrows](https://cloud.githubusercontent.com/assets/5324562/8459163/bc3623e2-1ff1-11e5-91a4-3d36b8a879e9.png)

How can it be fixed?

It works fine on Android 5.1 so my guess is that something not supported is being used.

**Comment by Joqus** [comment]
I see it seems to be the same thing as issue #266 but in the exemple I just downloaded this error keeps happening.

**Comment by birfincankafein** [comment]
And what is the result? All component's alignment in arrow's parent layout, is not setted. When I fork library and set their allignment it works.

**Comment by thomasdao** [comment]
This should now be fixed with version 2.2.0
