### ISSUE TITLE
calendar resizing itself

### ISSUE THREAD

**Issue by razikatz94** [roomorama/Caldroid#289]
I am using caldroid in a tab as part of a viewpager. When the caldroid tab is first created the calendar is the correct size, but after being idle for awhile it resizes itself so that the width is the same but the height is much smaller.

**Comment by secretgu** [comment]
Hi, I see you close this issue and I am wondering how do you fix it or walk around it? I am still having this issue.

Thanks.

**Comment by razikatz94** [comment]
I believe I fixed this issue by increasing the viewpagers offscreen page
limit so the tab with the calendar wouldn't ever be recreated

**Comment by secretgu** [comment]
Thanks! That does the trick. I also find another way around which is having a wrapper fragment with a layout containing a LinearLayout and then replace that LinearLayout with a CaldroidFragment instance in Fragment#onViewCreated method.

**Comment by secretgu** [comment]
This is what I find in CaldroidSampleActivity.java, BTW.
