### ISSUE TITLE
how to change today back color

### ISSUE THREAD

**Issue by shree-ram** [roomorama/Caldroid#291]
I need to change calendar by default selection today(Red-Grey) should change to grey color(full grey).I tried to change in file red_border_gray_bg or delete the file it again overwrite the same file whenever clear project or sync project.

**Comment by jagatb880** [comment]
Calendar cal = Calendar.getInstance();
                    cal.add(Calendar.DATE, 0);
                    Date currentDay = cal.getTime();
                    currentColors(currentDay);


public void currentColors(Date currentDay) {
        if (caldroidFragment != null) {
            caldroidFragment.setBackgroundResourceForDate(R.color.red,
                    currentDay);
            caldroidFragment.setTextColorForDate(R.color.white, currentDay);
        }
    }

**Comment by thomasdao** [comment]
@jagatb880 thanks for helping out
