### ISSUE TITLE
Won't show "calendar_title_view" properly

### ISSUE THREAD

**Issue by birfincankafein** [roomorama/Caldroid#292]
I set up your sample on my phone directly. Library has an allignment issues on Android 4.4.4 Here is screenshot. Where is the arrows?

![device-2015-07-21-043624](https://cloud.githubusercontent.com/assets/5882310/8791345/3a8dc8ba-2f62-11e5-965f-16ef401ff87e.png)

**Comment by Joqus** [comment]
I have the same issue. I have already created issue #287

**Comment by thomasdao** [comment]
This should now be fixed
