### ISSUE TITLE
CalendarHelper doesn't handle device changing timezones when setting MIN_DATE

### ISSUE THREAD

**Issue by deandalm** [roomorama/Caldroid#294]
Issue is that CalendarHelper using a static SimpleDateFormat and doesn't handle device changing timezones.

Steps to reproduce:
1. Instantiate CalendarFragment with MIN_DATE to today and device set to GMT-05:00 Central Daylight Time.
2. Change device to GMT-07:00 Pacific Daylight Time.
3. Instantiate a new CalendarFragment with MIN_DATE to today.
4. You can now select days in the past.

![calendar](https://cloud.githubusercontent.com/assets/3238102/8831708/c94c122a-3069-11e5-95f7-f6f059180992.png)

**Comment by thomasdao** [comment]
I've fixed this issue by re-init the static SimpleDateFormat when CaldroidFragment is instantiated, please checkout version 2.2.0
