### ISSUE TITLE
View by day

### ISSUE THREAD

**Issue by atoyansk** [roomorama/Caldroid#301]
Great Fragment! But is it possible to use it with view only by day?
Something like this:
![image](https://cloud.githubusercontent.com/assets/12189750/9068277/f39fc860-3ab8-11e5-9061-a44f1959ac0c.png)

If so, can you send any code example?
Thanks!

**Comment by AfanasievAnton** [comment]
i quite shure it could not. But it could be a new feature.

**Comment by thomasdao** [comment]
No Caldroid only display dates in month. You may need to develop your own fragment
