### ISSUE TITLE
Get date textview height

### ISSUE THREAD

**Issue by maphongba008** [roomorama/Caldroid#303]
I want to get date textview height in calendar, but I don't found any method in the library.
When I try to get the viewPager or gridView by caldroidFragment.getWeekdayGridView() in MainActivity, but they always return null.
How can I get date textView height? Thanks

**Comment by thomasdao** [comment]
I'm not sure if there's reliable way to get textview height. There're two types of TextView: normal or square. In square, height = parent width/7. For normal cell, it depends on padding and font size, I'm not sure how to get it. Btw if you use CaldroidListener, you can retrieve attributes of a cell:

```java
final CaldroidListener listener = new CaldroidListener() {

    @Override
    public void onSelectDate(Date date, View view) {
        // Retrieve attributes of view
    }

    @Override
    public void onChangeMonth(int month, int year) {
    }

    @Override
    public void onLongClickDate(Date date, View view) {
    }

    @Override
    public void onCaldroidViewCreated() {
    }

};

caldroidFragment.setCaldroidListener(listener);
```
