### ISSUE TITLE
Wrong month in calendar title on some devices

### ISSUE THREAD

**Issue by KKKoTTT** [roomorama/Caldroid#308]
Some users (not all of them) complain about the wrong month in the calendar title  - for example, "July 2015" instead of "August 2015".
Is it possible to solve this problem, for example, by making the month title locale-independent and hardcoding month names or smth?

**Comment by shellljx** [comment]
i have the same problem

**Comment by cashlo** [comment]
I found a fix for this issue, here's the pull request: https://github.com/roomorama/Caldroid/pull/312

**Comment by thomasdao** [comment]
The PR is merged, please try new version 2.2.0
