### ISSUE TITLE
Adapter Implemented?

### ISSUE THREAD

**Issue by zqillini4** [roomorama/Caldroid#310]
Hello, let me preface by saying I am still learning Android programming, but I had a question regarding the sample activity and adapter.  I don't see anywhere in the sample activity where the data is passed to the adapter, in fact, I don't see any adapter reference in the main Activity.  My ultimate goal is to be able to grab all the dates shown in the current month, and if they match the name of my hashset, then display the data in my hashset in the tv2 box, however I am struggling hardcore to try to figure out how to enumerate all dates shown in the current month view.

Any help is greatly appreciated, and I apologize if this is a super noob question.

--ZQ

**Comment by thomasdao** [comment]
In Caldroid 2.2.0, I added a function `getMonth` and `getYear` to return current month and year. You can use `CalendarHelper.getFullWeeks` to retrieve all dates shown in current month

**Comment by zqillini4** [comment]
Thanks thomasdao, that's just what I needed!

--Zach
