### ISSUE TITLE
How to change the below page(want to write the holidays) according to the change of month.(Caldroid)

### ISSUE THREAD

**Issue by jagatb880** [roomorama/Caldroid#318]

**Comment by thomasdao** [comment]
You can use Caldroid Listener https://github.com/roomorama/Caldroid#allow-user-to-select-a-date-and-inform-listener

**Comment by jagatb880** [comment]
public void onChangeMonth(int month, int year) {
if (2015 == year) {
                    switch (month) {
                        case 1:
                            setView();
                            break;
                        case 2:
                            setView();
                            break;
                        case 3:
                            setView();
                            break;
                        case 4:
                            setView();
                            break;
                        case 5:
                            setView();
                            break;
                        case 6:
                            setView();
                            break;
                        case 7:
                            setView();
                            break;
                        case 8:
                            setView();
                            break;
                        case 9:
                            setView();
                            break;
                        case 10:
                            setView();
                            break;
                        case 11:
                            setView();
                            break;
                        case 12:
                            setView();
                            break;
                        default:
                    }
                } else {
                    listHolder.removeAllViews();
                }

-----------------------------------------------
write your own logic for setView
