### ISSUE TITLE
after disable the dates also i found the tapable enable in that dates.How to resolve this.(caldroid))

### ISSUE THREAD

**Issue by jagatb880** [roomorama/Caldroid#320]

**Comment by thomasdao** [comment]
Thanks for reporting the issue. It's now fixed and will be pushed to Maven soon

**Comment by jagatb880** [comment]
private void setCustomResourceForRestDates() {
        ArrayList<Date> restdates = new ArrayList<Date>();

        String str_date = "01-01-2014";
        String end_date = "31-12-2016";

        SimpleDateFormat myFormat;

        myFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date startDate = null;
        try {
            startDate = myFormat.parse(str_date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        Date endDate = null;
        try {
            endDate = myFormat.parse(end_date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        long interval = 24 * 1000 * 60 * 60; // 1 hour in millis
        long endTime = endDate.getTime(); // create your endtime here, possibly using Calendar or Date
        long curTime = startDate.getTime();
        while (curTime <= endTime) {
            restdates.add(new Date(curTime));
            curTime += interval;
        }
        Date date = new Date();
        String inputString1, inputString2;
        for (int h = 0; h < restdates.size(); h++) {
            Date lDate = restdates.get(h);
            inputString3 = myFormat.format(lDate);
            inputString1 = myFormat.format(date);

            try {
                date3 = myFormat.parse(inputString3);
                date1 = myFormat.parse(inputString1);
                long restdiff = date3.getTime() - date1.getTime();
                long restdatee = restdiff / (1000 * 60 * 60 * 24);
                restday = (int) restdatee;
            } catch (ParseException e) {
                e.printStackTrace();
            }
            cal = Calendar.getInstance();
            cal.add(Calendar.DATE, restday);
            Date restHolidayDay = cal.getTime();
            restColors(restHolidayDay);
        }
    }
--------------------------------------------------------
public void restColors(Date restHolidayDay) {
        if (caldroidFragment != null) {
            caldroidFragment.setBackgroundResourceForDate(R.color.white,
                    restHolidayDay);
        }
    }
--------------------------------------------------
call this method -- setCustomResourceForRestDates() inside the onCreate Method
