### ISSUE TITLE
i want to disable the dates except highlighted dates 

### ISSUE THREAD

**Issue by jagatb880** [roomorama/Caldroid#321]
i want to disable the dates except highlighted dates ,there is already a function to disable the dates but i want to disable the whole year dates except current and highlighted dates.there is a function but after using that i found an error that after disabling also i can tab the date cell and the color is changing ,Sir pls resolve this issue.

**Comment by thomasdao** [comment]
This is not built-in feature in Caldroid. You can subclass Caldroid and do your own check. https://github.com/roomorama/Caldroid#allow-customized-cell-for-the-dates-gridview
