### ISSUE TITLE
How to set the month on months ie(from Jan to Dec of one year)

### ISSUE THREAD

**Issue by jagatb880** [roomorama/Caldroid#322]
How to set the range so that i can able to see only from jan to dec of current year.in the exsisting caldroid it is showing the current year,previous yaer and also next,next,next year.I want ot disable all other year except current year.

**Comment by AfanasievAnton** [comment]
I think you should add it by yourself.
Something like if/else check. If the date is gliching out of desired range, you can simple disable the navigation forward/backward(depend on date you want to stop the action). its a little bit "hack" but i think its can be simpest and fastest solution.

**Comment by jagatb880** [comment]
the how to disable the navigation
Lets take an example after going to dec of 2015 i want to disable the navigation,after disabling i am unable to go back ie to nov month of 2015.there is no reference of left arrow and right arrow ,by using which i can disable it .there is only on method like setShowNavigationArrow,if i disable it the i am not able to come back again to the nov month after comming to the dec .

**Comment by AfanasievAnton** [comment]
well...i looked quite quickly on the source code. From what i saw - you can simply retrieve your arrowButtons (left and right) from CaldroidFragment and the you can override their onClickListeners in such way, that you can tell them do nothing if they suppose to do nothing.
something like:
Button leftArrow = calFragment.getLeftArrowButton();
leftArrow.setOnClickListener(new OnClickListener(){
@override onClick(){
if(shouldShowNextMonth){
calFragment.prevMonth();

}
}

});

**Comment by jagatb880** [comment]
there is no shouldShowNextMonth in caldroid for check the condition

**Comment by AfanasievAnton** [comment]
of course there is no "shouldShowNextMonth" in Caldroid. Thats suppose to be your own check.
you need to create your own boolean called something like shouldShowNextMonth and set it to true, until you reach the condition where you dont want the month to be changed. and there set it to false.
well its really something really basic. if its still hard for you to understand, i suggest you to step a side from trying to implement somebodys 3-rd party library and focus on base programming logic.

**Comment by jagatb880** [comment]
Thank q Sir.

**Comment by AfanasievAnton** [comment]
you are welcome.

**Comment by thomasdao** [comment]
@AfanasievAnton thanks for helping :+1:
