### ISSUE TITLE
Cant find CaldroidFragment.selectedBackgroundDrawable in 2.2.0 release

### ISSUE THREAD

**Issue by scorpionking2k5** [roomorama/Caldroid#330]
I want to use the property CaldroidFragment.selectedBackgroundDrawable to set bg color for selected dates but I cant find this property in the lib. I have taken the latest release com.roomorama:caldroid:2.2.0

Has this property been removed?

**Comment by thomasdao** [comment]
Yes this property is removed, Caldroid now should be customized via theme. https://github.com/roomorama/Caldroid#custom-theme, for example:

```xml
    <style name="CaldroidDefaultDarkCell" parent="CaldroidDefaultCell">
        <item name="android:textColor">@color/cell_text_color_dark</item>
        <item name="android:background">@drawable/cell_bg_dark</item>
    </style>
```
