### ISSUE TITLE
Caldroid calendar in android

### ISSUE THREAD

**Issue by sukumarkathir** [roomorama/Caldroid#331]
Hi,I'm Sukumar. First of all thank you for gave such a wonder full calendar.Really very nice.
But i need your help for add some feature.

1.When i show calendar to user,it include booked date(Red colour).It's working fine.
But i want manage session like Morning or Evening.
My client want show booked date Red colour as well as whether it's Morning(M) or Evening(E) below that date.So how to set two textview below the date(Left side M and Right side E) within square?

2.Also the textview color represent green or red?red mean booked.Green mean available.

Thank you.
I hope you understand my question.If not mean just send your mail id.I will send that screen shot.

Kindly help me.
Sukumar G.
sukumarkathir@ymail.com.

**Comment by sukumarkathir** [comment]
Like this.I want.
![screenshot_2015-10-01-18-57-09](https://cloud.githubusercontent.com/assets/12151654/10275031/bb765b5a-6b61-11e5-99da-a8790a34993e.png)

**Comment by thomasdao** [comment]
You probably need to supply your own cell layout to Caldroid, please see instruction at https://github.com/roomorama/Caldroid#allow-customized-cell-for-the-dates-gridview

**Comment by sukumarkathir** [comment]
Thank you very much for your  reply.I'll try that. If I have face any issues,I will  inform.
