### ISSUE TITLE
How to capitalize only first letter in CaldroidDefaultMonthName

### ISSUE THREAD

**Issue by azizimusa** [roomorama/Caldroid#337]
I dont want to re-create CaldroidFragment class inside my project. Any other way to do it with custom style?

**Comment by thomasdao** [comment]
You can access `getWeekdayGridView()` method inside a CaldroidListener and provide your own adapter

**Comment by thomasdao** [comment]
Sorry I misunderstood your question, you should subclass candroidfragment and override refreshMonthTitleTextView() method.
