### ISSUE TITLE
Days of each month in a single row from 1 to 31 (or how many days in a month)

### ISSUE THREAD

**Issue by obaslan** [roomorama/Caldroid#338]
Hi There,
Do you know if it is possible to show the days in a month as a single row? The main issue is how do I get rid of the few days of the previous month and the next month. Because I can simply delete the GridView with the id "weekday_gridview" and not worry about matching the day names but how can I easly get rid of the extra days?

**Comment by thomasdao** [comment]
It's not possible for Caldroid to do this yet
