### ISSUE TITLE
how to display only two months from today ?

### ISSUE THREAD

**Issue by gr8guyramesh** [roomorama/Caldroid#339]

**Comment by thomasdao** [comment]
That's not possible right now in Caldroid

**Comment by gr8guyramesh** [comment]
Hi thomasdao,

Thanks for your information. can you please tell me how to disable particular dates while open the calendar Is it possible?

**Comment by thomasdao** [comment]
Please read the documentation https://github.com/roomorama/Caldroid#set-min--max-date

**Comment by gr8guyramesh** [comment]
Hi,
I have to disable dates at first open the calendar using setdisable() method. but after swipe the calendar or click the right arrow its worked....Is it possible to disable whenever open the calendar...
