### ISSUE TITLE
[HELP] Change background for certain dates .

### ISSUE THREAD

**Issue by niranjan94** [roomorama/Caldroid#34]
Hi, I'm trying to highlight certain dates in Caldroid and i'm using a HashMap and A custom Function for parsing a String into a Date variable .. But, it is not working .. What have i done wrong here ?

``` java
        // CUSTOM FUNCTION FOR PARSING STRING TO DATA
    public Date ParseDate(String date_str)
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd MMM yyyy");
        Date dateStr = null;
        try {
            dateStr = formatter.parse(date_str);
        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return dateStr;     
    }

        // SETTING THE BACKGROUND
    // Create a hash map
    HashMap hm = new HashMap();
    // Put elements to the map
        hm.put(ParseDate("Jun 14 2013"), R.color.blue);
        hm.put(ParseDate("Jun 16 2013"), R.color.green);
        hm.put(ParseDate("Jun 18 2013"), R.color.blue);
        hm.put(ParseDate("Jun 20 2013"), R.color.green);
        hm.put(ParseDate("Jun 22 2013"), R.color.blue);
    if (caldroidFragment != null) {
            caldroidFragment.setBackgroundResourceForDates(hm);
        }
```

So, what is wrong here ?? Any help would be greatly appreciated ...

**Comment by asifmoin7766** [comment]
I am new in android. I am using caldroid in my main activity and I have to perform events across the highlighted dates please tell me
1. how to get dates of caldroid to compare specific dates?
2. how to highlight the specific dates of caldroid

**Comment by mandeep91** [comment]
getting null pointer exception on caldroidFragment.setBackgroundDrawableForDates(hm);
can anyone tell m new in android
