### ISSUE TITLE
Add version changelog

### ISSUE THREAD

**Issue by Maragues** [roomorama/Caldroid#344]
It'd be nice knowing what changes from version to version.

If at least you published the releases in github, we would see the commits for each release.

Thanks

**Comment by thomasdao** [comment]
I used to have a section in README to describe what's changed, but don't have the discipline to update it every release... But you are right, it's good to know what's changes. I will create a tag from version 2.3.2 and above so anyone interested can just look at the diff. Thanks for the suggestion btw
