### ISSUE TITLE
How to Select Dates programiticaly

### ISSUE THREAD

**Issue by prasoonpv** [roomorama/Caldroid#365]
Iam Trying to select dates programitically, please tell me how to do this

**Comment by carlosandresSanchez** [comment]
With this method :  `caldroidFragment.setSelectedDates(Date date,Date date);`

Later, you have to call :  

` caldroidFragment.refreshView();`

**Comment by prasoonpv** [comment]
Thank  you for replay.
I already found it.
Caldroid is nice.
