### ISSUE TITLE
Cannot resolve gradle dependancy

### ISSUE THREAD

**Issue by Master-Zangetsu** [roomorama/Caldroid#374]
Android studio cannot resolve gradle dependancy.

`dependencies {
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.roomorama:caldroid:3.0.0'
}`

Receiving error: 30,13 failed to resolve com.roomorama:caldroid:3.0.0
All my other dependencies are resolving fine.

**Comment by Master-Zangetsu** [comment]
Never mind, I was being an idiot.

Issue was with my proxy settings.

**Comment by aicioara** [comment]
I am unsure how to install this. @Master-Zangetsu How did you get to that point?

I use Android Studio 2.0 

I added this line to `build.gradle (Module : app)`

``` gradle
compile 'com.roomorama:caldroid:3.0.1'
```

I did `Tools -> Android -> Sync Project with Gradle Files`. 

But nothing got downloaded.
