### ISSUE TITLE
Slow changing between Month, pls help it become smooth

### ISSUE THREAD

**Issue by staroflead** [roomorama/Caldroid#392]
As title says

**Comment by EsteveAguilera** [comment]
If you're using a custom adapter to show custom content on each day cell, the problem can be on the getView method...

Be shure that this method is not doing too much work, it should be executed in less than 0ms

**Comment by staroflead** [comment]
You are right, my getView is heavily coded with logic :+1: 
I will try to minimize the code in here.

**Comment by EsteveAguilera** [comment]
You can use the [Hugo library](https://github.com/JakeWharton/hugo) to track the getView method.

If my answer solves your question, you can close this issue.
