### ISSUE TITLE
Read transparent of background drawable (PNG) as transparent

### ISSUE THREAD

**Issue by timvahlbrock** [roomorama/Caldroid#446]
Hey there,
I want to use Caldroid in an App where the user is able to change the background Color of the Activity, but as I set the background drawable of the event the unset - normally transparent - part of the PNG is shown as grey. Does anyone know how to get the transparent parts of the drawable shown as transparent in the cell too?
Greetings

Me

**Comment by amorenew** [comment]
@timvahlbrock 
check my fork
https://github.com/amorenew/Caldroid/blob/master/sample.png
