### ISSUE TITLE
Getting "java.lang.IllegalStateException: Fragment already added: DateGridFragment" Exception

### ISSUE THREAD

**Issue by muditagarwal** [roomorama/Caldroid#80]
Hi,

I am using the library to show calendar view in my app, but everytime i am getting the following exception:

11-30 14:52:35.128: E/AndroidRuntime(3986): java.lang.IllegalStateException: Fragment already added: DateGridFragment{41b32840 #2 id=0x7f040020 android:switcher:2130968608:2}
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1175)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:616)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at com.antonyt.infiniteviewpager.InfinitePagerAdapter.finishUpdate(InfinitePagerAdapter.java:53)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at com.antonyt.infiniteviewpager.InfiniteViewPager.onMeasure(InfiniteViewPager.java:110)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:850)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2195)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.View.measure(View.java:15609)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2165)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1249)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1443)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.Choreographer.doCallbacks(Choreographer.java:579)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.Choreographer.doFrame(Choreographer.java:548)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.os.Handler.handleCallback(Handler.java:725)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.os.Handler.dispatchMessage(Handler.java:92)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.os.Looper.loop(Looper.java:153)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at android.app.ActivityThread.main(ActivityThread.java:5297)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at java.lang.reflect.Method.invokeNative(Native Method)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at java.lang.reflect.Method.invoke(Method.java:511)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
11-30 14:52:35.128: E/AndroidRuntime(3986):     at dalvik.system.NativeStart.main(Native Method)

**Comment by xmobia** [comment]
I got the same while trying to show multiple pages at same time.
Have you done it for Caldroid.
You can refer http://stackoverflow.com/questions/9468581/can-viewpager-have-multiple-views-in-per-page/15006910#15006910, what exactly I am asking.
