### ISSUE TITLE
The Caldroid is only partially displayed when using it as the listview header

### ISSUE THREAD

**Issue by HaohaoWang** [roomorama/Caldroid#84]
Like the picture shows:
![top calendar](https://f.cloud.github.com/assets/6041826/1765147/b59b1c9c-6731-11e3-8edc-27a578feb959.png)

It is a normal listview with a normal BaseAdapter, using the Caldroid as header..

**Comment by thomasdao** [comment]
I have fixed this issue in latest Caldroid 2.3.0, let me know if it works, thanks
